### ISSUE TITLE
Combine Inner.is_broken and Inner.resource into one enum

### ISSUE THREAD

**Issue by realcr** [realcr/async_mutex#3]
We currently have this code:

```rust
 pub struct Inner<T> {
    is_broken: bool,
    resource: Option<T>,
    awakeners: LinkedList<oneshot::Sender<T>>,
 }
```
This struct allows the state of resource = Some(...), while having is_broken = true.
I think that we can avoid this if we combine the state of `is_broken` and `resource`, maybe something like this:

```rust
enum ResourceState<T> {
    Broken,
    Pending,
    Present(T),
}
```
This way only legal states should be representable. What do you think?

**Comment by juchiast** [comment]
Do you mean "while having is_broken = false"?

**Comment by realcr** [comment]
I am not sure. I think that is_broken = true means that the resource was somehow lost.
So the following options could happen:
1. is_broken = false, resource = Some(...)
2. is_broken = false, resource = None
3. is_broken = true, resource = None

But the forth option, is_broken = true and resource = Some(...) should never happen, if I understand the code correctly. Therefore I propose to use an Enum. This can make sure that the illegal case will never occur.

**Comment by realcr** [comment]
Fixed by PR https://github.com/realcr/async_mutex/pull/7
